services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  ms-auth-usuarios-service:
    build: ./ms-auth-usuarios-service
    container_name: ms-auth-usuarios-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  ms-cliente-service:
    build: ./ms-cliente-service
    container_name: ms-cliente-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  ms-hotel-service:
    build: ./ms-hotel-service
    container_name: ms-hotel-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  ms-habitacion-service:
    build: ./ms-habitacion-service
    container_name: ms-habitacion-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  ms-disponibilidad-service:
    build: ./ms-disponibilidad-service
    container_name: ms-disponibilidad-service
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  ms-reserva-service:
    build: ./ms-reserva-service
    container_name: ms-reserva-service
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  ms-pago-service:
    build: ./ms-pago-service
    container_name: ms-pago-service
    ports:
      - "8087:8087"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  ms-resena-service:
    build: ./ms-resena-service
    container_name: ms-resena-service
    ports:
      - "8089:8089"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  ms-notificacion-service:
    build: ./ms-notificacion-service
    container_name: ms-notificacion-service
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  ms-servicio-adicional-service:
    build: ./ms-servicio-adicional-service
    container_name: ms-servicio-adicional-service
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
